AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
  NewCops: enable

Layout/BeginEndAlignment:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Include:
    - 'app/controllers/**/*.rb'
  Enabled: true
  Max: 20

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/ArrayCoercion:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ClassEqualityComparison:
  Enabled: true

Style/CombinableLoops:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'test/**/*'
    - 'app/presenters/**/*'

Style/DocumentationMethod:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false
